name: Make build kernel

on:
  push:
    branches:
      - buildkernel

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to make build kernel in FreeBSD
    env:
      MYTOKEN: ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          envs: "MYTOKEN MYTOKEN2"
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg -v
            pkg install -y git
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
          run: |
            echo "Running:"
            ls -alh
            cd work/test_action/test_action
            git checkout log
            git pull
            ls -alh

            LOG_NAME="buildkernel$(date '+%Y%m%d%H%M%S').log"

            # Add hardware information
            echo "===== Hardware Information =====" >> "$LOG_NAME"
            sysctl hw.model >> "$LOG_NAME"
            grep memory /var/run/dmesg.boot >> "$LOG_NAME"
            echo "===== Dmesg =====" >> "$LOG_NAME"
            dmesg >> "$LOG_NAME"

            echo "===== Make Output =====" >> "$LOG_NAME"
            git clone https://github.com/freebsd/freebsd-src.git /usr/src
            git config --global --add safe.directory /usr/src
            git config --global --add safe.directory /home/runner/work/test_action/test_action
            git pull -C /usr/src
            make -C /usr/src buildkernel >> "$LOG_NAME"

            git add .
            git commit -m "Auto-generated build files"
            git push
