name: Make build world

on:
  push:
    branches:
      - buildworld

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to make build world in FreeBSD
    env:
      MYTOKEN: ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          envs: "MYTOKEN MYTOKEN2"
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg -v
            pkg install -y git
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git clone https://github.com/freebsd/freebsd-src.git /usr/src
            git config --global --add safe.directory /usr/src
            git pull -C /usr/src
          run: |
            cd work/test_action/test_action
            git checkout log
            git pull

            LOG_NAME="buildworld-$(date '+%Y%m%d%H%M%S').log"

            # Add hardware information
            echo "===== Hardware Information =====" >> "$LOG_NAME"
            dmesg >> "$LOG_NAME"
            sysctl hw.model >> "$LOG_NAME"
            free -h >> "$LOG_NAME"

            # Continue with the existing build command
            make -C /usr/src buildworld >> "$LOG_NAME"

            git add .
            git commit -m "Auto-generated build files"
            git push
