name: Build test

on: [pull request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: ls -alh

      - name: Run build test
        run: |
          echo "Your PR has passed the build."
          exit 0